version: "3"
services:
  pstracker-nginx:
    build: ./nginx
    networks:
      - pstracker
    ports:
      - 80:80
  pstracker:
     build: ./src
     command: nodemon -L /src/index.js
     volumes:
       - ./src:/src
     networks:
       - pstracker
     ports:
       - 3000:3000
     environment:
       NODE_ENV: development
  pstracker-pusher:
    build:
      context: ./src
      dockerfile: pusher-docker
    command: nodemon -L /src/pusher.js
    volumes:
      - ./src:/src
    networks:
      - pstracker
    environment:
      NODE_ENV: development
  redis:
    image: redis
    networks:
      - pstracker
  pstracker-mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - pstracker
volumes:
    mongodbdata:
networks:
  pstracker: