version: "3"
services:
  pstracker-nginx:
    image: pstracker-nginx
    ports:
      - 80:80
    networks:
      - pstracker
  pstracker:
    image: pstracker
    networks:
      - pstracker
  redis:
    image: redis
    networks:
      - pstracker
  pstracker-mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - pstracker
volumes:
    mongodbdata:
networks:
  pstracker: