version: "3.2"
services:
  pstracker-nginx:
    image: 127.0.0.1:5000/pstracker-nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    networks:
      - pstracker
    deploy:
      replicas: 3
  pstracker:
    image: dukim/pstracker:latest
    networks:
      - pstracker
    environment:
      NODE_ENV: production
    deploy:
      replicas: 3
    depends_on:
      - redis
  pstracker-pusher:
    image: 127.0.0.1:5000/pstracker-pusher
    networks:
      - pstracker
    environment:
      NODE_ENV: production
    deploy:
      replicas: 1
  redis:
    image: redis
    networks:
      - pstracker
    deploy:
      replicas: 3
networks:
  pstracker:
    external: true