version: "3"
services:
  pstracker-nginx:
    image: 127.0.0.1:5000/pstracker-nginx
    ports:
      - 80:80
    network_mode: bridge
    networks:
      - pstracker
    deploy:
      replicas: 3
  pstracker:
    image: 127.0.0.1:5000/pstracker
    networks:
      - pstracker
    environment:
      NODE_ENV: production
    deploy:
      replicas: 3
    depends_on:
      - redis
      - pstracker-mongo
  redis:
    image: redis
    networks:
      - pstracker
    deploy:
      replicas: 3
  pstracker-mongo:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
    networks:
      - pstracker
volumes:
    mongodbdata:
networks:
  pstracker:
    external: true